[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 13

[font.bold]
family = "Sauce Code Pro Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Sauce Code Pro Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Sauce Code Pro Nerd Font Mono"
style = "Regular"

[terminal]

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"
