#!/bin/bash

xsetwacom set "HUION Huion Tablet Pad pad" "Button" "1" "key 1 "
xsetwacom set "HUION Huion Tablet Pad pad" "Button" "2" "key 2 "
# xsetwacom set "HUION Huion Tablet Pad pad" "Button" "3" "button +3 "
xsetwacom set "HUION Huion Tablet Pad pad" "Button" "8" "key Alt P "
# xsetwacom set "HUION Huion Tablet Pad pad" "Button" "9" "button +9 "
# xsetwacom set "HUION Huion Tablet Pad pad" "Button" "10" "button +10 "
# xsetwacom set "HUION Huion Tablet Pad pad" "Button" "11" "button +11 "
# xsetwacom set "HUION Huion Tablet Pad pad" "Button" "12" "button +12 "
# xsetwacom set "HUION Huion Tablet Pad pad" "Button" "13" "button +13 "
xsetwacom set "HUION Huion Tablet Pad pad" "Button" "14" "key Ctrl Z "
# xsetwacom set "HUION Huion Tablet Pad pad" "Button" "15" "button +15 "
# xsetwacom set "HUION Huion Tablet Pad pad" "Button" "16" "button +16 "
# xsetwacom set "HUION Huion Tablet Pad pad" "Button" "17" "button +17 "
# xsetwacom set "HUION Huion Tablet Pad pad" "ToolDebugLevel" "0"
# xsetwacom set "HUION Huion Tablet Pad pad" "TabletDebugLevel" "0"
# xsetwacom set "HUION Huion Tablet Pad pad" "Suppress" "2"
# xsetwacom set "HUION Huion Tablet Pad pad" "RawSample" "4"
# xsetwacom set "HUION Huion Tablet Pad pad" "Mode" "Absolute"
# xsetwacom set "HUION Huion Tablet Pad pad" "Touch" "off"
# xsetwacom set "HUION Huion Tablet Pad pad" "Gesture" "off"
# xsetwacom set "HUION Huion Tablet Pad pad" "ZoomDistance" "0"
# xsetwacom set "HUION Huion Tablet Pad pad" "ScrollDistance" "0"
# xsetwacom set "HUION Huion Tablet Pad pad" "TapTime" "250"
# xsetwacom set "HUION Huion Tablet Pad pad" "RelWheelUp" "1" "button +5 "
# xsetwacom set "HUION Huion Tablet Pad pad" "RelWheelDown" "2" "button +4 "
# xsetwacom set "HUION Huion Tablet Pad pad" "AbsWheelUp" "3" "button +4 "
# xsetwacom set "HUION Huion Tablet Pad pad" "AbsWheelDown" "4" "button +5 "
# xsetwacom set "HUION Huion Tablet Pad pad" "AbsWheel2Up" "5" "button +4 "
# xsetwacom set "HUION Huion Tablet Pad pad" "AbsWheel2Down" "6" "button +5 "
# xsetwacom set "HUION Huion Tablet Pad pad" "StripLeftUp" "1" "button +4 "
# xsetwacom set "HUION Huion Tablet Pad pad" "StripLeftDown" "2" "button +5 "
# xsetwacom set "HUION Huion Tablet Pad pad" "StripRightUp" "3" "button +4 "
# xsetwacom set "HUION Huion Tablet Pad pad" "StripRightDown" "4" "button +5 "
# xsetwacom set "HUION Huion Tablet Pad pad" "Threshold" "0"
# xsetwacom set "HUION Huion Tablet Pad pad" "BindToSerial" "0"
# xsetwacom set "HUION Huion Tablet Pad pad" "PanScrollThreshold" "13"


# xsetwacom set "HUION Huion Tablet Touch Strip pad" "Button" "1" "button +1 "
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "Button" "2"
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "Button" "3"
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "ToolDebugLevel" "0"
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "TabletDebugLevel" "0"
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "Suppress" "0"
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "RawSample" "4"
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "Mode" "Absolute"
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "Touch" "off"
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "Gesture" "off"
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "ZoomDistance" "0"
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "ScrollDistance" "0"
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "TapTime" "250"
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "RelWheelUp" "button +5 +5 "
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "RelWheelDown" "button +4 +4 "
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "AbsWheelUp" "button +4 +4 "
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "AbsWheelDown" "button +5 +5 "
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "AbsWheel2Up" "button +4 +4 "
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "AbsWheel2Down" "button +5 +5 "
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "StripLeftUp" "button +4 +4 "
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "StripLeftDown" "button +5 +5 "
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "StripRightUp" "button +4 +4 "
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "StripRightDown" "button +5 +5 "
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "Threshold" "0"
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "BindToSerial" "0"
# xsetwacom set "HUION Huion Tablet Touch Strip pad" "PanScrollThreshold" "13"
